export type TeamInfo = {
  id: string;
  abbreviation: string;
  primaryColor: string;
};

const TEAM_LOOKUP: Record<string, TeamInfo> = {
  // NBA
  "Atlanta Hawks":          { id: "atl", abbreviation: "ATL", primaryColor: "#E03A3E" },
  "Boston Celtics":         { id: "bos", abbreviation: "BOS", primaryColor: "#007A33" },
  "Brooklyn Nets":          { id: "bkn", abbreviation: "BKN", primaryColor: "#000000" },
  "Charlotte Hornets":      { id: "cha", abbreviation: "CHA", primaryColor: "#1D1160" },
  "Chicago Bulls":          { id: "chi", abbreviation: "CHI", primaryColor: "#CE1141" },
  "Cleveland Cavaliers":    { id: "cle", abbreviation: "CLE", primaryColor: "#860038" },
  "Dallas Mavericks":       { id: "dal", abbreviation: "DAL", primaryColor: "#00538C" },
  "Denver Nuggets":         { id: "den", abbreviation: "DEN", primaryColor: "#0E2240" },
  "Detroit Pistons":        { id: "det", abbreviation: "DET", primaryColor: "#C8102E" },
  "Golden State Warriors":  { id: "gsw", abbreviation: "GSW", primaryColor: "#1D428A" },
  "Houston Rockets":        { id: "hou", abbreviation: "HOU", primaryColor: "#CE1141" },
  "Indiana Pacers":         { id: "ind", abbreviation: "IND", primaryColor: "#002D62" },
  "Los Angeles Clippers":   { id: "lac", abbreviation: "LAC", primaryColor: "#C8102E" },
  "Los Angeles Lakers":     { id: "lal", abbreviation: "LAL", primaryColor: "#552583" },
  "Memphis Grizzlies":      { id: "mem", abbreviation: "MEM", primaryColor: "#5D76A9" },
  "Miami Heat":             { id: "mia", abbreviation: "MIA", primaryColor: "#98002E" },
  "Milwaukee Bucks":        { id: "mil", abbreviation: "MIL", primaryColor: "#00471B" },
  "Minnesota Timberwolves": { id: "min", abbreviation: "MIN", primaryColor: "#0C2340" },
  "New Orleans Pelicans":   { id: "nop", abbreviation: "NOP", primaryColor: "#0C2340" },
  "New York Knicks":        { id: "nyk", abbreviation: "NYK", primaryColor: "#006BB6" },
  "Oklahoma City Thunder":  { id: "okc", abbreviation: "OKC", primaryColor: "#007AC1" },
  "Orlando Magic":          { id: "orl", abbreviation: "ORL", primaryColor: "#0077C0" },
  "Philadelphia 76ers":     { id: "phi", abbreviation: "PHI", primaryColor: "#006BB6" },
  "Phoenix Suns":           { id: "phx", abbreviation: "PHX", primaryColor: "#1D1160" },
  "Portland Trail Blazers": { id: "por", abbreviation: "POR", primaryColor: "#E03A3E" },
  "Sacramento Kings":       { id: "sac", abbreviation: "SAC", primaryColor: "#5A2D81" },
  "San Antonio Spurs":      { id: "sas", abbreviation: "SAS", primaryColor: "#C4CED4" },
  "Toronto Raptors":        { id: "tor", abbreviation: "TOR", primaryColor: "#CE1141" },
  "Utah Jazz":              { id: "uta", abbreviation: "UTA", primaryColor: "#002B5C" },
  "Washington Wizards":     { id: "was", abbreviation: "WAS", primaryColor: "#002B5C" },

  // NFL
  "Arizona Cardinals":      { id: "ari", abbreviation: "ARI", primaryColor: "#97233F" },
  "Atlanta Falcons":        { id: "atl", abbreviation: "ATL", primaryColor: "#A71930" },
  "Baltimore Ravens":       { id: "bal", abbreviation: "BAL", primaryColor: "#241773" },
  "Buffalo Bills":          { id: "buf", abbreviation: "BUF", primaryColor: "#00338D" },
  "Carolina Panthers":      { id: "car", abbreviation: "CAR", primaryColor: "#0085CA" },
  "Chicago Bears":          { id: "chi", abbreviation: "CHI", primaryColor: "#0B162A" },
  "Cincinnati Bengals":     { id: "cin", abbreviation: "CIN", primaryColor: "#FB4F14" },
  "Cleveland Browns":       { id: "cle", abbreviation: "CLE", primaryColor: "#311D00" },
  "Dallas Cowboys":         { id: "dal", abbreviation: "DAL", primaryColor: "#003594" },
  "Denver Broncos":         { id: "den", abbreviation: "DEN", primaryColor: "#FB4F14" },
  "Detroit Lions":          { id: "det", abbreviation: "DET", primaryColor: "#0076B6" },
  "Green Bay Packers":      { id: "gb",  abbreviation: "GB",  primaryColor: "#203731" },
  "Houston Texans":         { id: "hou", abbreviation: "HOU", primaryColor: "#03202F" },
  "Indianapolis Colts":     { id: "ind", abbreviation: "IND", primaryColor: "#002C5F" },
  "Jacksonville Jaguars":   { id: "jac", abbreviation: "JAC", primaryColor: "#006778" },
  "Kansas City Chiefs":     { id: "kc",  abbreviation: "KC",  primaryColor: "#E31837" },
  "Las Vegas Raiders":      { id: "lv",  abbreviation: "LV",  primaryColor: "#000000" },
  "Los Angeles Chargers":   { id: "lac", abbreviation: "LAC", primaryColor: "#0080C6" },
  "Los Angeles Rams":       { id: "lar", abbreviation: "LAR", primaryColor: "#003594" },
  "Miami Dolphins":         { id: "mia", abbreviation: "MIA", primaryColor: "#008E97" },
  "Minnesota Vikings":      { id: "min", abbreviation: "MIN", primaryColor: "#4F2683" },
  "New England Patriots":   { id: "ne",  abbreviation: "NE",  primaryColor: "#002244" },
  "New Orleans Saints":     { id: "no",  abbreviation: "NO",  primaryColor: "#D3BC8D" },
  "New York Giants":        { id: "nyg", abbreviation: "NYG", primaryColor: "#0B2265" },
  "New York Jets":          { id: "nyj", abbreviation: "NYJ", primaryColor: "#125740" },
  "Philadelphia Eagles":    { id: "phi", abbreviation: "PHI", primaryColor: "#004C54" },
  "Pittsburgh Steelers":    { id: "pit", abbreviation: "PIT", primaryColor: "#FFB612" },
  "San Francisco 49ers":    { id: "sf",  abbreviation: "SF",  primaryColor: "#AA0000" },
  "Seattle Seahawks":       { id: "sea", abbreviation: "SEA", primaryColor: "#002244" },
  "Tampa Bay Buccaneers":   { id: "tb",  abbreviation: "TB",  primaryColor: "#D50A0A" },
  "Tennessee Titans":       { id: "ten", abbreviation: "TEN", primaryColor: "#4B92DB" },
  "Washington Commanders":  { id: "was", abbreviation: "WAS", primaryColor: "#773141" },

  // MLB
  "Arizona Diamondbacks":   { id: "ari", abbreviation: "ARI", primaryColor: "#A71930" },
  "Baltimore Orioles":      { id: "bal", abbreviation: "BAL", primaryColor: "#DF4601" },
  "Boston Red Sox":         { id: "bos", abbreviation: "BOS", primaryColor: "#BD3039" },
  "Chicago Cubs":           { id: "chc", abbreviation: "CHC", primaryColor: "#0E3386" },
  "Chicago White Sox":      { id: "cws", abbreviation: "CWS", primaryColor: "#27251F" },
  "Cincinnati Reds":        { id: "cin", abbreviation: "CIN", primaryColor: "#C6011F" },
  "Cleveland Guardians":    { id: "cle", abbreviation: "CLE", primaryColor: "#00385D" },
  "Colorado Rockies":       { id: "col", abbreviation: "COL", primaryColor: "#33006F" },
  "Detroit Tigers":         { id: "det", abbreviation: "DET", primaryColor: "#0C2C56" },
  "Houston Astros":         { id: "hou", abbreviation: "HOU", primaryColor: "#002D62" },
  "Kansas City Royals":     { id: "kc",  abbreviation: "KC",  primaryColor: "#004687" },
  "Los Angeles Angels":     { id: "laa", abbreviation: "LAA", primaryColor: "#BA0021" },
  "Los Angeles Dodgers":    { id: "lad", abbreviation: "LAD", primaryColor: "#005A9C" },
  "Miami Marlins":          { id: "mia", abbreviation: "MIA", primaryColor: "#00A3E0" },
  "Milwaukee Brewers":      { id: "mil", abbreviation: "MIL", primaryColor: "#12284B" },
  "Minnesota Twins":        { id: "min", abbreviation: "MIN", primaryColor: "#002B5C" },
  "New York Mets":          { id: "nym", abbreviation: "NYM", primaryColor: "#002D72" },
  "New York Yankees":       { id: "nyy", abbreviation: "NYY", primaryColor: "#003087" },
  "Oakland Athletics":      { id: "oak", abbreviation: "OAK", primaryColor: "#003831" },
  "Philadelphia Phillies":  { id: "phi", abbreviation: "PHI", primaryColor: "#E81828" },
  "Pittsburgh Pirates":     { id: "pit", abbreviation: "PIT", primaryColor: "#27251F" },
  "San Diego Padres":       { id: "sd",  abbreviation: "SD",  primaryColor: "#2F241D" },
  "San Francisco Giants":   { id: "sf",  abbreviation: "SF",  primaryColor: "#FD5A1E" },
  "Seattle Mariners":       { id: "sea", abbreviation: "SEA", primaryColor: "#0C2C56" },
  "St. Louis Cardinals":    { id: "stl", abbreviation: "STL", primaryColor: "#C41E3A" },
  "Tampa Bay Rays":         { id: "tb",  abbreviation: "TB",  primaryColor: "#092C5C" },
  "Texas Rangers":          { id: "tex", abbreviation: "TEX", primaryColor: "#003278" },
  "Toronto Blue Jays":      { id: "tor", abbreviation: "TOR", primaryColor: "#134A8E" },
  "Washington Nationals":   { id: "was", abbreviation: "WAS", primaryColor: "#AB0003" },

  // NHL
  "Anaheim Ducks":          { id: "ana", abbreviation: "ANA", primaryColor: "#F47A38" },
  "Arizona Coyotes":        { id: "ari", abbreviation: "ARI", primaryColor: "#8C2633" },
  "Boston Bruins":          { id: "bos", abbreviation: "BOS", primaryColor: "#FFB81C" },
  "Buffalo Sabres":         { id: "buf", abbreviation: "BUF", primaryColor: "#003087" },
  "Calgary Flames":         { id: "cgy", abbreviation: "CGY", primaryColor: "#C8102E" },
  "Carolina Hurricanes":    { id: "car", abbreviation: "CAR", primaryColor: "#CC0000" },
  "Chicago Blackhawks":     { id: "chi", abbreviation: "CHI", primaryColor: "#CF0A2C" },
  "Colorado Avalanche":     { id: "col", abbreviation: "COL", primaryColor: "#6F263D" },
  "Columbus Blue Jackets":  { id: "cbj", abbreviation: "CBJ", primaryColor: "#002654" },
  "Dallas Stars":           { id: "dal", abbreviation: "DAL", primaryColor: "#006847" },
  "Detroit Red Wings":      { id: "det", abbreviation: "DET", primaryColor: "#CE1126" },
  "Edmonton Oilers":        { id: "edm", abbreviation: "EDM", primaryColor: "#FF4C00" },
  "Florida Panthers":       { id: "fla", abbreviation: "FLA", primaryColor: "#041E42" },
  "Los Angeles Kings":      { id: "lak", abbreviation: "LAK", primaryColor: "#111111" },
  "Minnesota Wild":         { id: "min", abbreviation: "MIN", primaryColor: "#154734" },
  "Montreal Canadiens":     { id: "mtl", abbreviation: "MTL", primaryColor: "#AF1E2D" },
  "Nashville Predators":    { id: "nsh", abbreviation: "NSH", primaryColor: "#FFB81C" },
  "New Jersey Devils":      { id: "njd", abbreviation: "NJD", primaryColor: "#CE1126" },
  "New York Islanders":     { id: "nyi", abbreviation: "NYI", primaryColor: "#00539B" },
  "New York Rangers":       { id: "nyr", abbreviation: "NYR", primaryColor: "#0038A8" },
  "Ottawa Senators":        { id: "ott", abbreviation: "OTT", primaryColor: "#C52032" },
  "Philadelphia Flyers":    { id: "phi", abbreviation: "PHI", primaryColor: "#F74902" },
  "Pittsburgh Penguins":    { id: "pit", abbreviation: "PIT", primaryColor: "#FCB514" },
  "San Jose Sharks":        { id: "sjs", abbreviation: "SJS", primaryColor: "#006D75" },
  "Seattle Kraken":         { id: "sea", abbreviation: "SEA", primaryColor: "#001628" },
  "St. Louis Blues":        { id: "stl", abbreviation: "STL", primaryColor: "#002F87" },
  "Tampa Bay Lightning":    { id: "tbl", abbreviation: "TBL", primaryColor: "#002868" },
  "Toronto Maple Leafs":    { id: "tor", abbreviation: "TOR", primaryColor: "#003E7E" },
  "Utah Hockey Club":       { id: "uta", abbreviation: "UTA", primaryColor: "#6CAEDF" },
  "Vancouver Canucks":      { id: "van", abbreviation: "VAN", primaryColor: "#00205B" },
  "Vegas Golden Knights":   { id: "vgk", abbreviation: "VGK", primaryColor: "#B4975A" },
  "Washington Capitals":    { id: "wsh", abbreviation: "WSH", primaryColor: "#041E42" },
  "Winnipeg Jets":          { id: "wpg", abbreviation: "WPG", primaryColor: "#041E42" },
};

export function lookupTeam(name: string): TeamInfo {
  if (TEAM_LOOKUP[name]) return TEAM_LOOKUP[name];
  // Fallback: derive abbreviation from initials, use a neutral color
  const abbreviation = name
    .split(" ")
    .map((w) => w[0])
    .join("")
    .toUpperCase()
    .slice(0, 3);
  return {
    id: name.toLowerCase().replace(/[^a-z]/g, "-").replace(/-+/g, "-"),
    abbreviation,
    primaryColor: "#4a4a6a",
  };
}
